import { HelloDocument } from "@/autogenerated/documents/hello";
import { Page } from "@/components/Page";
import { ProseContainer } from "@/components/ProseContainer";
import { withGraphQL } from "@/graphql/urql";
import { useQuery } from "urql";

function Hello() {
  const [hello] = useQuery({ query: HelloDocument });

  if (!hello.error && !hello.data) {
    return <p className="animate-pulse">Loading...</p>;
  }

  return <p>{hello.data?.hello}</p>;
}

function Index() {
  return (
    <Page>
      <ProseContainer>
        <h1>Welcome to Graphlatte</h1>
        <Hello />
      </ProseContainer>
    </Page>
  );
}

export default withGraphQL(Index);
