import { LoginDocument } from "@/autogenerated/documents/login";
import { Page } from "@/components/Page";
import { ProseContainer } from "@/components/ProseContainer";
import { withGraphQL } from "@/graphql/urql";
import { useRouter } from "next/router";
import { useState } from "react";
import { useMutation } from "urql";

function Login() {
  const router = useRouter();
  const [name, setName] = useState("");
  const [password, setPassword] = useState("");
  const [, loginMutation] = useMutation(LoginDocument);

  async function login() {
    const result = await loginMutation({
      name,
      password,
    });

    if (result.data?.login?.id) {
      router.push("/dashboard");
    }
  }

  return (
    <Page>
      <ProseContainer>
        <h1>Login</h1>
        <div className="flex flex-col items-start gap-2">
          <div>Name</div>
          <input
            className="w-full max-w-sm rounded border-gray-200 p-2"
            type="text"
            value={name}
            onChange={(event) => setName(event.target.value)}
          />
          <div>Password</div>
          <input
            className="mb-4 w-full max-w-sm rounded border-gray-200 p-2"
            type="password"
            value={password}
            onChange={(event) => setPassword(event.target.value)}
          />
          <button className="rounded bg-black px-8 text-white" onClick={login}>
            Login
          </button>
        </div>
      </ProseContainer>
    </Page>
  );
}

export default withGraphQL(Login);
