import { RegisterDocument } from "@/autogenerated/documents/register";
import { Page } from "@/components/Page";
import { ProseContainer } from "@/components/ProseContainer";
import { withGraphQL } from "@/graphql/urql";
import { useRouter } from "next/router";
import { useState } from "react";
import { useMutation } from "urql";

function Register() {
  const router = useRouter();
  const [name, setName] = useState("");
  const [password, setPassword] = useState("");
  const [, registerMutation] = useMutation(RegisterDocument);

  async function register() {
    const result = await registerMutation({
      name,
      password,
    });

    if (result.data?.register?.id) {
      router.push("/login");
    }
  }

  return (
    <Page>
      <ProseContainer>
        <h1>Register</h1>
        <div className="flex flex-col items-start gap-2">
          <div>Name</div>
          <input
            className="w-full max-w-sm rounded border-gray-200 p-2"
            type="text"
            value={name}
            onChange={(event) => setName(event.target.value)}
          />
          <div>Password</div>
          <input
            className="mb-4 w-full max-w-sm rounded border-gray-200 p-2"
            type="password"
            value={password}
            onChange={(event) => setPassword(event.target.value)}
          />
          <button
            className="rounded bg-black px-8 text-white"
            onClick={register}
          >
            Register
          </button>
        </div>
      </ProseContainer>
    </Page>
  );
}

export default withGraphQL(Register);
